// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhcnvmjqiwxnbbctkadj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoY252bWpxaXd4bmJiY3RrYWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODAwNDgsImV4cCI6MjA2OTQ1NjA0OH0.sYoomQp-ia34-iOybcC7UaB4d3ZriZFQxOBEAcz097s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});